image: node:12

stages:
  - prepare
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

prepare:
  stage: prepare
  script:
    - npm install --progress=false
  artifacts:
    paths:
      - node_modules/
      - package.json
      - package-lock.json

unit test:
  stage: test
  script:
    - npm run lint
    - npm run test

build site:
  stage: build
  script:
    - npm run build
